version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: production  # Use the production stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=postgres_db
      - DB_NAME=nodeAngular
      - DB_PORT=5432
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
      target: production  # Use the production stage
    ports:
      - "4200:4200"
    depends_on:
      - backend

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nodeAngular
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: